kind: pipeline
name: docker-alpine

clone:
  disable: true

steps:
  - name: clone
    image: plugins/git
    when:
      event:
        - tag
        - pull_request
    recursive: true


  - name: docker
    image: plugins/docker
    when:
      event:
        - tag
        - pull_request
    settings:
      repo: storezhang/alpine
      dockerfile: ./Dockerfile
      mirror: https://docker.mirrors.ustc.edu.cn
      storage_driver: vfs
      username: storezhang
      password:
        from_secret: docker_password
      auto_tag: true
      force_tag: true


volumes:
  - name: deps
    temp: {}
