kind: secret
name: token_docker
get:
  path: secrets
  name: token_docker_dronestock
---

kind: secret
name: password_ccr
get:
  path: secrets
  name: password_ccr
---

kind: secret
name: id_feishu
get:
  path: secrets
  name: id_feishu
---

kind: secret
name: secret_feishu
get:
  path: secrets
  name: secret_feishu
---


kind: pipeline
type: docker
name: 发布


clone:
  disable: true


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git
    pull: always

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/docker
    pull: always
    privileged: true
    volumes:
      - name: docker
        path: /var/lib/docker
    environment:
      PASSWORD_DOCKER:
        from_secret: token_docker
      PASSWORD_CCR:
        from_secret: password_ccr
    settings:
      repository: storezhang/alpine
      tag: match(file('Dockerfile'), '.*(FROM alpine:(.*)\\\\s*).*')[2]
      targets:
        - arch: arm32v7
        - arch: arm64v8
        - arch: amd64
      registries:
        - username: storezhang
          password: $${PASSWORD_DOCKER}
        - hostname: ccr.ccs.tencentyun.com
          username: "160290688"
          password: $${PASSWORD_CCR}
          required: true

  - name: 通知
    image: ccr.ccs.tencentyun.com/dronestock/feishu
    pull: always
    when:
      status:
        - success
        - failure
    settings:
      id:
        from_secret: id_feishu
      secret:
        from_secret: secret_feishu
      notfound:
        id: storezhang


volumes:
  - name: docker
    host:
      path: /var/lib/cache/docker
